manifest = "c1c608e09b8074e67844f877f91d006cc7d0d927168ee7620abcf6a5ff8c6055"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "1.61.0" ]
revision = "8e838521dcf7fd8f27bfd1b7d602152c9c0406a4"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.61.0" ]
revision = "8b257f9d05d2cbcec375c85469ed248b3ab1298f"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.61.0" ]
revision = "d1bfb4fc64744904219b6772e1363d4d2302c3a7"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.61.0" ]
revision = "dee6af64de0ff366213b9e1ecf647e66db5d6780"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.61.0" ]
revision = "42200144daa6a31d26ad814386f32dad9f546b09"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.61.0" ]
revision = "3a632ba2dd41c6a1c307605fc0fa9f219362dad3"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.61.0" ]
revision = "562dcc896e3f522fa14785d77cdfba99234118e3"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.61.0" ]
revision = "348bd128b0c1bf1456b0343ab6e494dfc4467771"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.61.0" ]
revision = "8c9c6042069b3ef6837337b9217bea5849ff75f2"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.61.0" ]
revision = "0a30b4d3b4a9b37208396aa5024355b79f8246df"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.61.0" ]
revision = "1f6d0b1c5fa6ed6fc57d5d9c067fcc20c8f728f9"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.61.0" ]
revision = "b16936965d33dc00ca3fbb872c3a9e769db26195"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.61.0" ]
revision = "8f165ea5147d2c0e5b70df342a02f16929276510"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.61.0" ]
revision = "778bedbf611762f73758ed20f9d8f76ede5f6292"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.61.0" ]
revision = "d25454aaa50d50639af46be51d6698850b021379"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.61.0" ]
revision = "3d06eb6cc3da48719c55ec183c94349d68b66996"
