manifest = "da760cd41fbc3a8234e38f997a0644fe77c308eaddd57f115932f321ce5bb81f"

[[dependency]]
package = "github.com/buckaroo-pm/boost-assert"
target = "//:assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[lock]]
name = "github.com/buckaroo-pm/boost-assert"
revision = "cae7816110ba208a2290d02d128594e8809c9075"

[[lock]]
name = "github.com/buckaroo-pm/boost-config"
revision = "e60ff9d2778e3d2a6969859783a7c5bcc424f9a2"
